### ISSUE TITLE
Board index communities

### ISSUE THREAD

**Issue by Tealk** [LemmyNet/lemmyBB#11]
Shouldn't all subscribed communities be visible on the index page?

**Comment by Nutomic** [comment]
It shows all communities, but at most 10. You can increase the limit in the line below, or change it to Subscribed.

https://github.com/LemmyNet/lemmyBB/blob/main/src/api/community.rs#L16

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmyBB/commit/333723eead06cc9aadb5efc7c8c81e0c39570cc7
https://github.com/LemmyNet/lemmyBB/commit/d8251a31c02489f5ab8e226bb89867eff61dda3c
