### ISSUE TITLE
h1 color and margin

### ISSUE THREAD

**Issue by Tealk** [LemmyNet/lemmyBB#21]
The h1 headline is displayed very poorly
![image](https://user-images.githubusercontent.com/12276250/197333498-5932bd5b-84f2-47bc-8570-c21b7a02f132.png)

https://github.com/LemmyNet/lemmyBB/blob/a4ff63d68e7dc1a762cb8bcb0c44c94daf0aec05/assets/styles/prosilver/colours.css#L380
add above
```
.content h1, .panel h1 {
	color: #115098;
	border-bottom-color: #CCCCCC;
}
```

https://github.com/LemmyNet/lemmyBB/blob/a4ff63d68e7dc1a762cb8bcb0c44c94daf0aec05/assets/styles/prosilver/content.css#L338
add above
```
.content h1, .panel h1 {
  font-weight: bold;
  border-bottom: 1px solid transparent;
  font-size: 2em;
  margin-top: 1em;
  margin-bottom: 0.5em;
  padding-bottom: 0.5em;
}
```

With the above changes it would look like this
![image](https://user-images.githubusercontent.com/12276250/197333746-2a13ec66-ea7e-494d-b8f5-9d4af7747d1f.png)

**Comment by Nutomic** [comment]
Please make a pull request. Though i would prefer to put any css changes in assets/styles/lemmybb.css like the other pr, so that lemmybb can easily be used with other phpbb themes.

**Comment by Tealk** [comment]
i have to try that first, if there are no problems, because i want to avoid such aids like !importent.
