### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmyBB#24]
LemmyBB is compatible with phpBB themes. Need to write documentation and add some config options to facilitate this.

We can also pick some nice foss themes and include them directly with lemmybb.

**Comment by Nutomic** [comment]
Sadly this wont work because phpbb themes include their own template files, so they wont work with the default template :(

**Comment by poVoq** [comment]
So how would one replicate some simple phpBB themes for lemmyBB?

I have an old forum I want to replace with LemmyBB and it would be nice to at least have the look a bit similar and add a site icon etc.

**Comment by Tealk** [comment]
Hello @poVoq 

Since the theming of phpbb does not follow any guideline, you will probably have to adapt the theme manually.

The best way to do this is to use the existing templates (https://github.com/LemmyNet/lemmyBB/tree/main/templates) and adapt them accordingly.

**Comment by poVoq** [comment]
Will there be at least a simple way to replace the site avatar and so on?

**Comment by Tealk** [comment]
What is the site avatar?

**Comment by poVoq** [comment]
The image on the top left corner, same as on Lemmy-ui.

**Comment by Tealk** [comment]
You mean the logo?
Please create a separate issue for it, then you can add it later. 
![image](https://user-images.githubusercontent.com/12276250/199001586-db31c851-c52a-4313-8e58-599e7a72d86b.png)

**Comment by Nutomic** [comment]
See https://github.com/LemmyNet/lemmyBB/commit/eb00776068081fdbb76fd4d2cc8d40702f45fafd for the logo.

Im reopening this issue as there is interest in theming.

**Comment by Nutomic** [comment]
Closing this in favor of #48 because this issue is already quite long.
