### ISSUE TITLE
Forum functionality

### ISSUE THREAD

**Issue by loid345** [LemmyNet/lemmyBB#3]
Great idea. I have a question.  Will it be a full-fledged forum with similar functionality as phpbb?

**Comment by Nutomic** [comment]
Depends what you mean by similar. It will have the functionality of Lemmy, while looking like phpBB. I think phpBB has a lot of different permissions which Lemmy doesnt have, so it wont be possible to implement those.

**Comment by loid345** [comment]
> Depends what you mean by similar. It will have the functionality of Lemmy, while looking like phpBB. I think phpBB has a lot of different permissions which Lemmy doesnt have, so it wont be possible to implement those.

I think that if support for subcategories and tags is added to the functionality of lemmy, then this can already be considered a full-fledged forum. Such a platform will be a very big success. But the name should be changed to something more attractive to users, for example rustbb

**Comment by Nutomic** [comment]
Adding categories and maybe tags makes sense, but i'm not sure how it would work (partly because i havent used any forum software with those features in a long time). It would be helpful if you could open issues for these features, and describe how exactly they should work.

I am also open to change the name, but rustbb doesnt sound any better than lemmybb to me.

Also in case you havent noticed, you can now test lemmybb by running it locally, and connecting to your lemmy instance.

**Comment by loid345** [comment]
> Adding categories and maybe tags makes sense, but i'm not sure how it would work (partly because i havent used any forum software with those features in a long time). It would be helpful if you could open issues for these features, and describe how exactly they should work.
> 
> I am also open to change the name, but rustbb doesnt sound any better than lemmybb to me.
> 
> Also in case you havent noticed, you can now test lemmybb by running it locally, and connecting to your lemmy instance.

Thanks for the answer. But I think what I write about is obvious things. There is no forum engine without tags and child categories. This is the basis of any forum. Now discourse is the main forum engine on the Internet, but you can easily compete with it. All the same, this is powerful rust, not ruby
https://trends.builtwith.com/cms/Discourse

**Comment by loid345** [comment]
Why I suggest calling the engine rusbb is because it hints that the engine is based on rust, by analogy as phpbb or nodebb. That is, the engine is ten times more productive than its competitors and requires fewer resources, and the name is still free. This means that the name of the engine is the best advertisement and thousands of users will want to have a forum on such an engine and contribute to the development of the platform, including financial. I myself am ready, even today and always, to donate thousands of dollars for such an engine, since current engines cannot compete with a platform written in rust. There are no such platforms and there won't be in the coming years. Rust is not ruby. It would be cool to create the coolest open source forum engine in the world. Users need such a platform yesterday!

**Comment by Nutomic** [comment]
@loid345 I tried to send you an email, but the address in your profile doesnt work. Can you contact me using the address in my profile?

**Comment by loid345** [comment]
> @loid345 I tried to send you an email, but the address in your profile doesnt work. Can you contact me using the address in my profile?

I don't leave my real mailing address because I live under a bloody dictatorship and fight it, but I don't want to leave the country either. Can I write to you on your email?

**Comment by Nutomic** [comment]
Please do.
