### ISSUE TITLE
complete fedilink

### ISSUE THREAD

**Issue by Tealk** [LemmyNet/lemmyBB#31]
the full link should be displayed in the local community, so it may be difficult to know which instance it is.

![image](https://user-images.githubusercontent.com/12276250/198064910-a55cfb72-5231-451c-8b11-9a5c004a4c83.png)

**Comment by Nutomic** [comment]
If there is no domain displayed, its a local community. Lemmy-ui works the same way, and Mastodon also (for users).

**Comment by Tealk** [comment]
but the url of the lemmybb frontend is different from the server url?

as an example
https://lemmybb.rollenspiel.monster/viewforum?f=12
then i would search now `!rm_news@lemmybb.rollenspiel.monster`

in fediverse it is normally the case that if no domain is specified, the domain displayed in the address bar is used, but this is a fallacy with an alternative frontend

**Comment by Nutomic** [comment]
That makes sense. However, lemmybb doesnt know under which url it is being opened. I guess we could add an env var for the domain, but it would be easy to forget setting that.

**Comment by Nutomic** [comment]
Actually i dont think this is a problem, because the item you point out is a link, and the link url is the activitypub object id returned by Lemmy. So if you paste that link into a search field, it will always work.
