### ISSUE TITLE
[Bug]: Post comments from other instances don't show

### ISSUE THREAD

**Issue by JediMaster25** [LemmyNet/lemmyBB#60]
### Steps to reproduce

1. Copy https://heapoverflow.ml/c/linux to fedibb.ml search and click the result.
2. In other words visit https://fedibb.ml/view_forum?f=25
3. All posts have 0 comments even thought they actually should have comments.

### On which operating systems are you seeing the problem on?

- [ ] Wdinwos <- THIS IS A TYPO
- [X] Manjaro Linux

### On which browsers are you seeing the problem on?

- [X] Firefox 106.0.3

### Version

Don't know. Doesn't appear in the footer

**Comment by Nutomic** [comment]
Federation was broken on fedibb, i fixed that on friday. If you subscribed to a community before that day, the subscribe didnt go through and you have to do it again.

**Comment by JediMaster25** [comment]
I haven't subscribed. Just watching the community from fedibb.

**Comment by Nutomic** [comment]
Yes, and you will only see new replies which are made after you subscribe.
