### ISSUE TITLE
[Bug]: Making a post returns a 500 error

### ISSUE THREAD

**Issue by mu-arch** [LemmyNet/lemmyBB#62]
### Steps to reproduce

1. Go to https://fedibb.ml/view_forum?f=2
2. Click "New topic"
3. Create enter a title and body.
4. Click submit
5. You will get a 500 error

### On which operating systems are you seeing the problem on?

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Android
- [ ] iOS/iPadOS

### On which browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Other (please describe in more detail under Additional context)

**Comment by Nutomic** [comment]
Were you logged in? Only panic i can see in the logs seems to be from users who try to post without valid login.
