### ISSUE TITLE
Failed to start lemmy_bb

### ISSUE THREAD

**Issue by nixoye** [LemmyNet/lemmyBB#72]
### Question description

When running `systemctl status lemmy_bb.service`
I get this error
```

× lemmy_bb.service - lemmy_bb
     Loaded: loaded (/etc/systemd/system/lemmy_bb.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Thu 2022-12-22 06:22:10 UTC; 1min 4s ago
   Duration: 1ms
    Process: 21008 ExecStart=/opt/lemmyBB/target/release/lemmy_bb (code=exited, status=203/EXEC)
   Main PID: 21008 (code=exited, status=203/EXEC)
        CPU: 960us

Dec 22 06:22:09 g0v systemd[1]: lemmy_bb.service: Main process exited, code=exited, status=203/EXEC
Dec 22 06:22:09 g0v systemd[1]: lemmy_bb.service: Failed with result 'exit-code'.
Dec 22 06:22:10 g0v systemd[1]: lemmy_bb.service: Scheduled restart job, restart counter is at 5.
Dec 22 06:22:10 g0v systemd[1]: Stopped lemmy_bb.
Dec 22 06:22:10 g0v systemd[1]: lemmy_bb.service: Start request repeated too quickly.
Dec 22 06:22:10 g0v systemd[1]: lemmy_bb.service: Failed with result 'exit-code'.
Dec 22 06:22:10 g0v systemd[1]: Failed to start lemmy_bb
```

**Comment by Tealk** [comment]
What does the log say?
`journalctl -u lemmy_bb.service`

**Comment by nixoye** [comment]
systemd[1]: lemmy_bb.service: Failed with result 'exit-code'.
 systemd[1]: lemmy_bb.service: Scheduled restart job, restart counter is at 3.
 systemd[1]: Stopped lemmy_bb.
 systemd[1]: Started lemmy_bb.
 systemd[1]: lemmy_bb.service: Main process exited, code=exited, status=203/EXEC
systemd[1]: lemmy_bb.service: Failed with result 'exit-code'.
systemd[1]: lemmy_bb.service: Scheduled restart job, restart counter is at 4.
systemd[1]: Stopped lemmy_bb.
systemd[1]: Started lemmy_bb.
 systemd[955]: lemmy_bb.service: Failed to locate executable /opt/lemmyBB/target/release/lemmy_bb: No such>
systemd[955]: lemmy_bb.service: Failed at step EXEC spawning /opt/lemmyBB/target/release/lemmy_bb: No suc>
 systemd[1]: lemmy_bb.service: Main process exited, code=exited, status=203/EXEC
ystemd[1]: lemmy_bb.service: Failed with result 'exit-code'.
 systemd[1]: lemmy_bb.service: S

**Comment by Nutomic** [comment]
Seems like the file `/opt/lemmyBB/target/release/lemmy_bb` doesnt exist. Did you run `cargo build --release`? Maybe you used a different folder?

**Comment by nixoye** [comment]
@Nutomic I did. I followed the instructions step by step

**Comment by Nutomic** [comment]
So does the mentioned file exist at that path or not?

**Comment by Tealk** [comment]
Show us the following output
`ls -a /opt/lemmyBB/target/release`

**Comment by nixoye** [comment]
sorry, yes it does.

```
ls -a /opt/lemmyBB/target/release
.   .cargo-lock   build  examples     lemmy_bb
..  .fingerprint  deps   incremental  lemmy_bb.d
```

**Comment by nixoye** [comment]
@Nutomic after using the updated instructions for lemmybb i fixed my install on the lemmybb side. My only issue now is this unkown directive error for lemmy

`FAILED! => {"changed": true, "cmd": "nginx -s reload", "delta": "0:00:00.046506", "end": "2022-12-26 16:42:11.279902", "msg": "non-zero return code", "rc": 1, "start": "2022-12-26 16:42:11.233396", "stderr": "nginx: [emerg] unknown directive \"sdlimit_req_zone\" in /etc/nginx/sites-enabled/lemmybb.conf.save:1", "stderr_lines": ["nginx: [emerg] unknown directive \"sdlimit_req_zone\" in /etc/nginx/sites-enabled/lemmybb.conf.save:1"], "stdout": "", "stdout_lines": []}`

**Comment by Nutomic** [comment]
There shouldnt be any .conf.save file, it was probably created by your editor. You can safely delete it.
