### ISSUE TITLE
[Bug]: Invalid URL Created When Changing Pages On Topic List

### ISSUE THREAD

**Issue by TheNetNomad** [LemmyNet/lemmyBB#96]
### Steps to reproduce

1. Go to **https://lemmybb.rollenspiel.monster/view_forum?f=12**
2. In the upper right-hand corner, below the Login and Registration links, click either the "2" button or the ">" button to advance to the next page
3. This should take you to a 404 screen. Find viewforum in the resulting url, change it to view_forum, and you should arrive at the intended destination

Reproduced in Firefox, Chrome and Edge on Windows 10 on rollspiel.monster and on a private instance

### Version

0.2.2

### Additional context

Doing a quick search in the repo turns up src/routes/community.rs line 53:

`let pagination = Pagination::new(page, limit, format!("/viewforum?f={f}&"));`

Changing `viewforum` to `view_forum` there and recompiling seems to have fixed it on my own instance

**Comment by TheNetNomad** [comment]
This might be related to issue 94 (I had already started writing the ticket when I found the line with pagination and had already forgotten about that one, sorry!) but both the rollenspiel forum and the private forum are on their respective instances

**Comment by Nutomic** [comment]
Good explanation, with this I found the problem which was simply a typo. Turns out #94 was about the same thing but I completely misunderstood it.
